image: registry.gitlab.com/pages/hugo:latest

variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
  - hugo --ignoreCache --minify --gc -v
  artifacts:
    paths:
    - public
  only:
  - master

